server:
  port: 8022
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: 100MB
spring:
  datasource:
    url: jdbc:mysql://47.120.63.23:3306/zhny?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
#  redis:
#    url: jdbc:mysql://1.94.61.174:3306/carpooling?characterEncoding=utf8&useSSL=true
#    username: root
#    password: root
  flyway:
    # 是否启用flyway
    enabled: true
    # 不允许乱序执行
    out-of-order: false
    schemas: zhny
    table: flyway_schema_history
    encoding: UTF-8
    # 脚本位置
    locations: classpath:db/migration/test
    # 检测迁移脚本的路径是否存在，如不存在，则抛出异常
    fail-on-missing-locations: true
    # 在迁移时，是否校验脚本，假设V1.0__初始.sql已经迁移过了，在下次启动时会校验该脚本是否有变更过，则抛出异常
    validate-on-migrate: true
    # 到新的环境中数据库中有数据，且没有flyway_schema_history表时，是否执行迁移操作
    # 如果设置为false，在启动时会报错，并停止迁移；如果设置为true,则生成history表并完成所有的迁移。当前完全采用 flyway 管理，不设置基线
    baseline-on-migrate: false
    baseline-version: 0
    baseline-description: <<Flyway Baseline>>
#  mqtt:
#    #MQTT-服务器连接地址，如果有多个，用逗号隔开
#    host: tws://47.120.63.23:8083
#    #MQTT-连接服务器默认客户端ID
#    clientId: mqtt_id
#    #MQTT-用户名
#    username: admin
#    #MQTT-密码
#    password: admin
#    #MQTT-默认的消息推送主题，实际可在调用接口时指定
#    topic: zhny
#    #连接超时
#    timeout: 1000
#    #设置会话心跳时间
#    keepalive: 100


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
      id-type: assign_id
#  type-aliases-package: com.alpha.database.space.entity.dto

logging:
  config:  classpath:log4j2.xml

